obj-m += pim_drv.o
pim_drv-objs := pim_drv_main.o dma_probe.o pl_fops.o \
				ps_fops.o host_fops.o pim_mem_probe.o \
				pim_math/matmul.o pim_math/matmul_decoupled.o pim_math/elewise.o pim_math/lut.o
